import os
import argparse
from pathlib import Path
import sys

# --- Settings ---

# Identifies the location of the script (Root of the rules Repo)
RULES_REPO_ROOT = Path(os.path.abspath(__file__)).parent

# Mapping between the command you write and the actual folder
# If the name is identical (e.g., swiftui -> swiftui_rules), the script will guess it automatically
TECH_MAP = {
    "swiftui": "swiftui_rules",
    "flutter": "flutter_rules",
    "nest": "nestjs_rules",
    "nestjs": "nestjs_rules",
    "cloud": "cloud_functions",
    "mcp": "mcp"
}

# The files that will be created in the target project
TARGET_FILES = [
    ".cursorrules",
    ".agent/AGENTS.md",                 
    "GEMINI.md",                        
    ".github/copilot-instructions.md",  
    ".opencode/AGENTS.md",              
    "AGENTS.md"                         
]

def get_folder_content(tech_name):
    """
    Enters the appropriate folder, searches for core.md and other files, and returns the unified content.
    """
    # 1. Finding the folder name
    folder_name = TECH_MAP.get(tech_name, f"{tech_name}_rules")
    folder_path = RULES_REPO_ROOT / folder_name
    
    if not folder_path.exists():
        print(f"❌ Error: Folder '{folder_name}' not found in {RULES_REPO_ROOT}")
        print(f"   Available folders: {[d.name for d in RULES_REPO_ROOT.iterdir() if d.is_dir() and not d.name.startswith('.')]}")
        return None

    print(f"📂 Reading from: {folder_name}")

    # 2. Collecting all Markdown files in the folder
    md_files = list(folder_path.glob("*.md"))
    
    if not md_files:
        print(f"⚠️ Warning: No .md files found in {folder_name}")
        return None

    combined_content = ""
    
    # 3. Smart logic: core.md first, then the rest
    # We sort so that core.md is first
    md_files.sort(key=lambda f: 0 if f.name.lower() == 'core.md' else 1)

    for md_file in md_files:
        print(f"   ✅ Found rule: {md_file.name}")
        content = md_file.read_text(encoding='utf-8')
        combined_content += content + "\n\n"

    return combined_content

def sync_rules(tech_name):
    print(f"🚀 Starting Sync for: {tech_name}")
    print("-" * 40)

    # Phase A: Retrieving content from the appropriate folder
    full_content = get_folder_content(tech_name)
    
    if not full_content:
        print("⛔ Aborting: No content to sync.")
        sys.exit(1)

    # Adding signature
    full_content += "---\n> Auto-generated by sync_agents.py from central rules repo."

    # Phase B: Writing to the current project
    current_dir = Path.cwd()
    print("-" * 40)
    print(f"🎯 Injecting into Project: {current_dir.name}")

    count = 0
    for target in TARGET_FILES:
        target_path = current_dir / target
        
        # Creating parent directories if needed
        if target_path.parent != current_dir:
            target_path.parent.mkdir(parents=True, exist_ok=True)
            
        try:
            with open(target_path, 'w', encoding='utf-8') as f:
                f.write(full_content)
            count += 1
        except Exception as e:
            print(f"   ❌ Error writing {target}: {e}")

    print(f"✨ Success! Updated {count} configuration files.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("tech", help="Technology stack (e.g. swiftui, flutter, nest)")
    args = parser.parse_args()

    sync_rules(args.tech)