import pytest
from pathlib import Path
from unittest.mock import patch
import sys
import os

import sync_agents
from sync_agents import get_folder_content, sync_rules, TECH_MAP, TARGET_FILES


class TestGetFolderContentCombinesFiles:
    """Test case 1: get_folder_content correctly combines content from multiple
    markdown files, prioritizing core.md first."""

    def test_core_md_is_prioritized_first(self, tmp_path):
        """Verify core.md content appears before other markdown files."""
        # Create a tech folder with multiple markdown files
        tech_folder = tmp_path / "test_rules"
        tech_folder.mkdir()

        (tech_folder / "core.md").write_text("CORE CONTENT", encoding="utf-8")
        (tech_folder / "extra.md").write_text("EXTRA CONTENT", encoding="utf-8")
        (tech_folder / "another.md").write_text("ANOTHER CONTENT", encoding="utf-8")

        with patch.object(sync_agents, "RULES_REPO_ROOT", tmp_path):
            result = get_folder_content("test")

        assert result is not None
        # core.md should appear first
        core_pos = result.find("CORE CONTENT")
        extra_pos = result.find("EXTRA CONTENT")
        another_pos = result.find("ANOTHER CONTENT")

        assert core_pos < extra_pos
        assert core_pos < another_pos

    def test_combines_all_markdown_files(self, tmp_path):
        """Verify all markdown files are included in the combined content."""
        tech_folder = tmp_path / "mytech_rules"
        tech_folder.mkdir()

        (tech_folder / "file1.md").write_text("FILE1", encoding="utf-8")
        (tech_folder / "file2.md").write_text("FILE2", encoding="utf-8")
        (tech_folder / "file3.md").write_text("FILE3", encoding="utf-8")

        with patch.object(sync_agents, "RULES_REPO_ROOT", tmp_path):
            result = get_folder_content("mytech")

        assert "FILE1" in result
        assert "FILE2" in result
        assert "FILE3" in result


class TestGetFolderContentMissingFolder:
    """Test case 2: get_folder_content returns None and prints an error message
    when the specified tech folder does not exist."""

    def test_returns_none_for_nonexistent_folder(self, tmp_path):
        """Verify None is returned when folder doesn't exist."""
        with patch.object(sync_agents, "RULES_REPO_ROOT", tmp_path):
            result = get_folder_content("nonexistent")

        assert result is None

    def test_prints_error_for_nonexistent_folder(self, tmp_path, capsys):
        """Verify error message is printed when folder doesn't exist."""
        with patch.object(sync_agents, "RULES_REPO_ROOT", tmp_path):
            get_folder_content("nonexistent")

        captured = capsys.readouterr()
        assert "Error" in captured.out
        assert "nonexistent_rules" in captured.out


class TestSyncRulesCreatesTargetFiles:
    """Test case 3: sync_rules successfully creates all target files in the
    current directory with the combined content."""

    def test_creates_all_target_files(self, tmp_path):
        """Verify all TARGET_FILES are created with the correct content."""
        # Setup: create tech folder with content
        tech_folder = tmp_path / "rules_source" / "test_rules"
        tech_folder.mkdir(parents=True)
        (tech_folder / "core.md").write_text("TEST RULES CONTENT", encoding="utf-8")

        target_dir = tmp_path / "project"
        target_dir.mkdir()

        with patch.object(sync_agents, "RULES_REPO_ROOT", tmp_path / "rules_source"):
            with patch.object(Path, "cwd", return_value=target_dir):
                sync_rules("test")

        # Check all target files were created
        for target in TARGET_FILES:
            target_path = target_dir / target
            assert target_path.exists(), f"{target} should exist"
            content = target_path.read_text(encoding="utf-8")
            assert "TEST RULES CONTENT" in content

    def test_content_includes_signature(self, tmp_path):
        """Verify the auto-generated signature is appended."""
        tech_folder = tmp_path / "rules_source" / "demo_rules"
        tech_folder.mkdir(parents=True)
        (tech_folder / "core.md").write_text("DEMO", encoding="utf-8")

        target_dir = tmp_path / "project"
        target_dir.mkdir()

        with patch.object(sync_agents, "RULES_REPO_ROOT", tmp_path / "rules_source"):
            with patch.object(Path, "cwd", return_value=target_dir):
                sync_rules("demo")

        # Check signature in one of the files
        content = (target_dir / ".cursorrules").read_text(encoding="utf-8")
        assert "Auto-generated by sync_agents.py" in content


class TestSyncRulesCreatesParentDirectories:
    """Test case 4: sync_rules creates parent directories for target files
    if they do not already exist."""

    def test_creates_parent_directories(self, tmp_path):
        """Verify parent directories are created for nested target files."""
        tech_folder = tmp_path / "rules_source" / "test_rules"
        tech_folder.mkdir(parents=True)
        (tech_folder / "core.md").write_text("CONTENT", encoding="utf-8")

        target_dir = tmp_path / "project"
        target_dir.mkdir()

        # Ensure nested directories don't exist initially
        assert not (target_dir / ".agent").exists()
        assert not (target_dir / ".github").exists()
        assert not (target_dir / ".opencode").exists()

        with patch.object(sync_agents, "RULES_REPO_ROOT", tmp_path / "rules_source"):
            with patch.object(Path, "cwd", return_value=target_dir):
                sync_rules("test")

        # Verify directories were created
        assert (target_dir / ".agent").is_dir()
        assert (target_dir / ".github").is_dir()
        assert (target_dir / ".opencode").is_dir()

        # Verify files exist in those directories
        assert (target_dir / ".agent" / "AGENTS.md").exists()
        assert (target_dir / ".github" / "copilot-instructions.md").exists()
        assert (target_dir / ".opencode" / "AGENTS.md").exists()


class TestTechMapResolution:
    """Test case 5: The TECH_MAP correctly resolves short technology names
    (e.g., 'nest') to their corresponding folder names."""

    def test_nest_resolves_to_nestjs_rules(self):
        """Verify 'nest' maps to 'nestjs_rules'."""
        assert TECH_MAP.get("nest") == "nestjs_rules"

    def test_nestjs_resolves_to_nestjs_rules(self):
        """Verify 'nestjs' also maps to 'nestjs_rules'."""
        assert TECH_MAP.get("nestjs") == "nestjs_rules"

    def test_swiftui_resolves_correctly(self):
        """Verify 'swiftui' maps to 'swiftui_rules'."""
        assert TECH_MAP.get("swiftui") == "swiftui_rules"

    def test_flutter_resolves_correctly(self):
        """Verify 'flutter' maps to 'flutter_rules'."""
        assert TECH_MAP.get("flutter") == "flutter_rules"

    def test_cloud_resolves_correctly(self):
        """Verify 'cloud' maps to 'cloud_functions'."""
        assert TECH_MAP.get("cloud") == "cloud_functions"

    def test_mcp_resolves_correctly(self):
        """Verify 'mcp' maps to 'mcp'."""
        assert TECH_MAP.get("mcp") == "mcp"

    def test_unknown_tech_falls_back_to_default_pattern(self, tmp_path):
        """Verify unknown tech names use the {tech}_rules fallback pattern."""
        tech_folder = tmp_path / "unknown_rules"
        tech_folder.mkdir()
        (tech_folder / "core.md").write_text("UNKNOWN CONTENT", encoding="utf-8")

        with patch.object(sync_agents, "RULES_REPO_ROOT", tmp_path):
            result = get_folder_content("unknown")

        assert result is not None
        assert "UNKNOWN CONTENT" in result
